# Generated by Django 2.2.7 on 2020-05-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Out wear')], default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='lavel',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='S', max_length=1),
            preserve_default=False,
        ),
    ]
