# Generated by Django 2.2.7 on 2020-05-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200523_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='lavel',
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
        ),
    ]
